### ISSUE TITLE
dev start报错

### ISSUE THREAD

**Issue by wjun52** [bombayjs/bombayjs-server#1]
dev:
\bombayjs-server\node_modules\ioredis\built\redis\index.js:282:31)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
name: "ETIMEDOUTError"
pid: 16336
hostname: DESKTOP-BMEJ56P

start:
Internal Server Error, real status: 500

**Comment by aoping** [comment]
没装redis?
