### ISSUE TITLE
[Bug Report] 无法启动

### ISSUE THREAD

**Issue by ly525** [bombayjs/bombayjs-server#2]
运行步骤如下，无法启动，还请麻烦帮忙看下？

```
git clone https://github.com/bombayjs/bombayjs-server.git
cd bombayjs-server
cnpm i
npm run dev
```

运行环境：
```
node -v: v12.13.0
npm -v 6.12.0
tsc -v: Version 3.7.2
```

```bash
2020-01-15 12:42:02,952 INFO 21956 [master] agent_worker#1:21961 started (2793ms)

/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: [egg-core] load file: /Users/lambert/Temp/bombayjs-server/app/service/dimension.ts, error: ⨯ Unable to compile TypeScript:
app/service/dimension.ts(25,51): error TS2339: Property 'desc' does not exist on type 'TErrorInfo'.
app/service/dimension.ts(117,51): error TS2339: Property 'desc' does not exist on type 'TErrorInfo'.

    at createTSError (/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:261:12)
    at getOutput (/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:367:40)
    at Object.compile (/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/lambert/Temp/bombayjs-server/node_modules/_ts-node@7.0.1@ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.loadFile (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/utils/index.js:27:19)
    at getExports (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:199:23)
    at ContextLoader.parse (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:158:25)
    at ContextLoader.load (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToContext (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/loader/egg_loader.js:408:28)
    at AppWorkerLoader.loadService (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-core@4.17.4@egg-core/lib/loader/mixin/service.js:24:10)
[2020-01-15 12:42:06.308] [cfork:master:21956] worker:21964 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2020-01-15 12:42:06.308] [cfork:master:21956] don't fork, because worker:21964 will be kill soon
2020-01-15 12:42:06,308 INFO 21956 [master] app_worker#1:21964 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2020-01-15 12:42:06.309] [cfork:master:21956] worker:21964 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
2020-01-15 12:42:06,312 ERROR 21956 nodejs.AppWorkerDiedError: [master] app_worker#1:21964 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/master.js:510:21)
    at Master.emit (events.js:210:5)
    at Messenger.sendToMaster (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/utils/messenger.js:137:17)
    at Messenger.send (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/utils/messenger.js:102:12)
    at EventEmitter.<anonymous> (/Users/lambert/Temp/bombayjs-server/node_modules/_egg-cluster@1.26.0@egg-cluster/lib/master.js:353:22)
    at EventEmitter.emit (events.js:215:7)
    at ChildProcess.<anonymous> (internal/cluster/master.js:188:13)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
name: "AppWorkerDiedError"
pid: 21956
hostname: lamberts-MacBook-Pro.local

2020-01-15 12:42:06,313 ERROR 21956 [master] app_worker#1:21964 start fail, exiting with code:1
2020-01-15 12:42:06,313 ERROR 21956 [master] exit with code:1
2020-01-15 12:42:06,326 ERROR 21961 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
2020-01-15 12:42:06,329 ERROR 21961 [agent_worker] exit with code:110
Error: /Users/lambert/Temp/bombayjs-server/node_modules/_egg-bin@4.14.1@egg-bin/lib/start-cluster {"typescript":true,"declarations":true,"port":7002,"workers":1,"baseDir":"/Users/lambert/Temp/bombayjs-server","framework":"/Users/lambert/Temp/bombayjs-server/node_modules/egg"} exit with code 1
    at ChildProcess.<anonymous> (/Users/lambert/Temp/bombayjs-server/node_modules/_common-bin@2.8.3@common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bombayjs-server@1.0.0 dev: `egg-bin dev --port=7002`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bombayjs-server@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lambert/.npm/_logs/2020-01-15T04_42_06_350Z-debug.log
```

**Comment by ferying** [comment]
同问
